### ISSUE TITLE
Using LOOM on Ubuntu

### ISSUE THREAD

**Issue by hassaanirshad** [cadets/loom#20]
Hi,

I am using LOOM on Ubuntu and had some questions. I have created a fork of LOOM [here](https://github.com/hassaanirshad/loom).

There is a small program which I am building and executing using the script [here](https://github.com/hassaanirshad/loom/commit/9dcb52fb8a5987fa94458e016e9f147f090c85f1#diff-5639c9e6e96bad93157a654e1a3aff5d) and it is working fine. To build, there are minor differences when compared with tests in LOOM [here](https://github.com/hassaanirshad/loom/tree/master/test). 

Using the file LOOM policy file [here](https://github.com/hassaanirshad/loom/blob/master/ubuntu/test.policy) gives the error in the file [here](https://github.com/hassaanirshad/loom/blob/master/ubuntu/error.buildAndExecute). The change that causes the error to be generated is the function name '[a-zA-Z0-9_]+' in the policy file. The reason for using that function name is to instrument all functions.

1) Can you please give me any insight on what could be causing the issue mentioned above?
2) In the function [here](https://github.com/hassaanirshad/loom/blob/master/ubuntu/test.c#L10), is it possible to get the values of strings logged (for example, "hello") rather than the value of the pointer (for example, 0xabcdef)?

Thank you.

**Comment by bkidney** [comment]
@hassaanirshad Is there any other output to the failed build other than the stack dump you included in the issue? Specifically I am interested in any messages about VarArg functions. I have been able to reproduce a similar error, but it seems to relate to instrumenting printf(). Digging further into that now.

**Comment by hassaanirshad** [comment]
@bkidney Yes, there is more output than that in the file that I shared before [here](https://github.com/hassaanirshad/loom/blob/master/ubuntu/error.buildAndExecute). Copy paste error. The first line in the error is the following:

`Warning: VarArg functions cannot be fully instrumented.`

And the rest of the error was the same on the re-run.

Thank you.

**Comment by bkidney** [comment]
Could you try the changes from the pull request #21 to see if they solve your problem?

**Comment by hassaanirshad** [comment]
Yes, the error mentioned before does NOT occur after using the changes from pull request [#21](https://github.com/cadets/loom/pull/21). The differences in the output than before are the following:

1) New line (repeated) in output: `Skipping llvm debug function: llvm.dbg.declare`
2) New line in output: `Warning: VarArg functions cannot be instrumented.`
3) The [`printf`](https://man7.org/linux/man-pages/man3/printf.3.html) function call instrumentation shows with only the first argument. Example: `call printf: 0x400a82`
4) The [`printf`](https://man7.org/linux/man-pages/man3/printf.3.html) function return instrumentation seen as (example): `return printf: 10 0x400a82`

Thank you

**Comment by bkidney** [comment]
@hassaanirshad I have been unable to replicate the `printf` only showing the first argument. Could you send me a simplified `.c` file and policy file that show this bug?

**Comment by hassaanirshad** [comment]
@bkidney Thank you for making the changes. I am using the policy file [test.policy](https://github.com/hassaanirshad/loom/blob/master/ubuntu/test.policy) and the `.c` code is [test.c](https://github.com/hassaanirshad/loom/blob/master/ubuntu/test.c). The output of running the script [buildAndExecute.sh](https://github.com/hassaanirshad/loom/blob/master/ubuntu/buildAndExecute.sh) with the code in [issue-20-stack-dump-when-using-wildcards](https://github.com/cadets/loom/tree/issue-20-stack-dump-when-using-wildcards) is pasted below:

>1 Warning: Trying to instrument vararg function printf. Loom does not support instrumenting vararg functions.
      2 Warning: Trying to instrument vararg function printf. Loom does not support instrumenting vararg functions.
      3 enter main: 4 0x7ffdd073b548
      4 call printf: 0x400da2
      5 STDOUT::0 main(argc=3return printf: 21 0x400da2
      6 call printf: 0x400dba
      7 , argv[0]=areturn printf: 11 0x400dba
      8 call printf: 0x400dba
      9 , argv[1]=breturn printf: 11 0x400dba
     10 call printf: 0x400dba
     11 , argv[2]=creturn printf: 11 0x400dba
     12 call printf: 0x400cf5
     13 )
     14 return printf: 2 0x400cf5
     15 call function_void_return_no_arg:
     16 enter function_void_return_no_arg:
     17 call printf: 0x400ccc
     18 STDOUT::void function_void_return_no_arg()
     19 return printf: 43 0x400ccc
     20 leave function_void_return_no_arg: %void%
     21 return function_void_return_no_arg:
     22 call function_int_return_int_long_float_charp_arg: 901 902 903.140015 0x400dc8
     23 enter function_int_return_int_long_float_charp_arg: 901 902 903.140015 0x400dc8
     24 call printf: 0x400cf8
     25 STDOUT::101 function_int_return_int_long_float_charp_arg(a=901, b=902, c=903.140015, d=nine-o-four)
     26 return printf: 100 0x400cf8
     27 leave function_int_return_int_long_float_charp_arg: 101 901 902 903.140015 0x400dc8
     28 return function_int_return_int_long_float_charp_arg: 101 901 902 903.140015 0x400dc8
     29 call function_charp_return_int_long_float_charp_arg: 801 802 803.140015 0x400dd4
     30 enter function_charp_return_int_long_float_charp_arg: 801 802 803.140015 0x400dd4
     31 call printf: 0x400d50
     32 STDOUT::hello function_int_return_int_long_float_charp_arg(a=801, b=802, c=803.140015, d=eight-o-four)
     33 return printf: 103 0x400d50
     34 leave function_charp_return_int_long_float_charp_arg: 0x400d4a 801 802 803.140015 0x400dd4
     35 return function_charp_return_int_long_float_charp_arg: 0x400d4a 801 802 803.140015 0x400dd4
     36 test_struct.test_int store: 0x7ffdd073b428 701
     37 test_struct.test_charp store: 0x7ffdd073b428 0x400de1
     38 test_struct.test_int load: 0x7ffdd073b428 701
     39 test_struct.test_charp load: 0x7ffdd073b428 0x400de1
     40 call printf: 0x400ded
     41 STDOUT:struct test_struct{test_int=701, test_charp=seven-o-two}
     42 return printf: 64 0x400ded
     43 leave main: 0 4 0x7ffdd073b548

One example of `printf` is at lines `24` and `26` which corresponds to the code in `test.c` [here](https://github.com/hassaanirshad/loom/blob/master/ubuntu/test.c#L19). Please let me know if this is not clear.

**Comment by bkidney** [comment]
Perfect. I am working on a solution to the problem. Will let you know when I have something for you to test.

**Comment by hassaanirshad** [comment]
Thank you! and for sharing the patch for printing char pointers.

**Comment by bkidney** [comment]
I have committed a fix for the truncated logging of `printf` in #21. Please give it a try and let me know if this fixes your problem.

That branch also includes a unsafe printf logger incorporates the changes from the patch I sent you. If you set your logger to `unsafe_printf` in your policy file the logger will print strings instead of giving the `char *` pointer address.

**Comment by hassaanirshad** [comment]
@bkidney Thank you very much! The arguments to variadic functions are being printed as well printing of char pointer values with the logger option `unsafe_printf` with the code in #21. Thank you.

**Comment by bkidney** [comment]
Fixed and changes merges into master.
